from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [("store_app", "0008_useractivitylog"), migrations.swappable_dependency(settings.AUTH_USER_MODEL)]
    operations = [
        migrations.CreateModel(name="QuotationSettings", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),("company_name", models.CharField(blank=True,max_length=180)),("address",models.TextField(blank=True)),("gstin",models.CharField(blank=True,max_length=30)),("phone",models.CharField(blank=True,max_length=30)),("email",models.EmailField(blank=True,max_length=254)),("bank_name",models.CharField(blank=True,max_length=120)),("account_name",models.CharField(blank=True,max_length=120)),("account_number",models.CharField(blank=True,max_length=60)),("ifsc",models.CharField(blank=True,max_length=30)),("branch",models.CharField(blank=True,max_length=120)),("terms",models.TextField(blank=True,default="Quotation valid for 15 days.")),("updated_at",models.DateTimeField(auto_now=True))]),
        migrations.CreateModel(name="Quotation", fields=[("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),("number",models.CharField(max_length=40,unique=True)),("customer_name",models.CharField(max_length=180)),("customer_phone",models.CharField(blank=True,max_length=30)),("customer_email",models.EmailField(blank=True,max_length=254)),("customer_address",models.TextField(blank=True)),("customer_gstin",models.CharField(blank=True,max_length=30)),("quote_date",models.DateField()),("valid_until",models.DateField(blank=True,null=True)),("shipment_details",models.TextField(blank=True)),("notes",models.TextField(blank=True)),("subtotal",models.DecimalField(decimal_places=2,default=0,max_digits=14)),("tax_total",models.DecimalField(decimal_places=2,default=0,max_digits=14)),("shipping_amount",models.DecimalField(decimal_places=2,default=0,max_digits=14)),("grand_total",models.DecimalField(decimal_places=2,default=0,max_digits=14)),("created_at",models.DateTimeField(auto_now_add=True)),("created_by",models.ForeignKey(null=True,on_delete=django.db.models.deletion.SET_NULL,to=settings.AUTH_USER_MODEL))],options={"ordering":("-created_at",)}),
        migrations.CreateModel(name="QuotationItem", fields=[("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),("product_name",models.CharField(max_length=180)),("sku",models.CharField(blank=True,max_length=80)),("hsn_code",models.CharField(blank=True,max_length=30)),("quantity",models.DecimalField(decimal_places=2,max_digits=12)),("unit_price",models.DecimalField(decimal_places=2,max_digits=14)),("gst_percentage",models.DecimalField(decimal_places=2,max_digits=5)),("taxable_amount",models.DecimalField(decimal_places=2,max_digits=14)),("tax_amount",models.DecimalField(decimal_places=2,max_digits=14)),("total_amount",models.DecimalField(decimal_places=2,max_digits=14)),("product",models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,to="store_app.product")),("quotation",models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name="items",to="store_app.quotation"))]),
    ]
